
# server description, configuration and behaviour;
#
server:
    port: ${EVENTS_COLLECTOR_PORT:8090}

    base-path: /@parent.artifactId@
    title: @project.name@
    description: @project.description@
    version: @project.version@

    the-host-name: your-host.net

    shutdown: graceful

    repository:
      type: ${EVENTS_COLLECTOR_REPOSITORY_TYPE:memory}
      url:  ${EVENTS_COLLECTOR_REPOSITORY_URL:}

    error:
      include-message:  always

# actuator parameters
#
management.endpoints.web.exposure.include: health, info

# logging configuration
#
logging:
  level:
    web:  INFO
    org:
      springframework:
        web:  INFO

# swagger configuraton
#
springfox.documentation.swagger-ui.base-url:  ${server.base-path}
